# DX 601 Week 11 Homework

## Introduction

In this homework, you will practice working with systems of linear equations and review previous weeks' material.

## Example Code

You may find it helpful to refer to this GitHub repository of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx500-examples
* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Shared Imports

Do not install or use any additional modules.
Installing additional modules may result in an autograder failure resulting in zero points for some or all problems.

In [200]:
import math
import sys

In [201]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats
import sklearn.linear_model

## Shared Data

### Vineyard Data

This data set attempts to predict yields for a small vineyard in Lake Erie in 1991 based on the yields in the previous years.
Each row of the data set represents the yields of a row of the vineyard.
See https://github.com/EpistasisLab/pmlb/blob/master/datasets/192_vineyard/metadata.yaml for more information.

In [202]:
vineyard = pd.read_csv("https://github.com/EpistasisLab/pmlb/raw/refs/heads/master/datasets/192_vineyard/192_vineyard.tsv.gz", sep="\t")
vineyard.head()

lugs_1989  lugs_1990  target
0        1.0        5.0     9.5
1        3.0        8.0    17.5
2        3.0       11.0    18.0
3        3.0        9.0    20.0
4        5.0        9.5    20.5

In [203]:
vineyard_inputs = vineyard[["lugs_1989", "lugs_1990"]]
vineyard_inputs.head()

lugs_1989  lugs_1990
0        1.0        5.0
1        3.0        8.0
2        3.0       11.0
3        3.0        9.0
4        5.0        9.5

In [204]:
vineyard_target = vineyard["target"]

## Problems

### Problem 1

Set `p1` to the value of $x$ after solving the following system of linear equations.

\begin{array}{rcl}
3x & = & 4.2 \\
\end{array}


In [205]:
# YOUR CHANGES HERE

p1 = 4.2/3

In [206]:
p1

1.4000000000000001

### Problem 2

Set `p2` to be a tuple of `(x, y)` where $x$ and $y$ are the solution to the following system of linear equations.

\begin{array}{rcl}
3x + 2y & = & 8.6 \\
2x + 5y & = & 13.8 \\
\end{array}


Hint: Just do this by hand.

In [207]:
# YOUR CHANGES HERE
# 3x + 2y = 8.6  =>   2y = 8.6 - 3x  ==>  y = 4.3 - 3/2(x)
# 2x + 5y = 13.8  =>  2x + 5(4.3 - 3/2(x)) = 13.8  => 2x + 21.5 - 7.5x = 13.8  =>  -5.5x = -7.7  => x=1.4
# x=1.4  =>  3(1.4) + 2y = 8.6  =>  4.2 + 2y = 8.6   => 2y = 4.4  => y=2.2

p2 = (1.4, 2.2) 

In [208]:
p2

(1.4, 2.2)

### Problem 3

Set `p3` to be the x intercept of the following equation.

\begin{array}{rcl}
4x + 2y + 3z & = & 12 \\
\end{array}

In [209]:
# YOUR CHANGES HERE
# 4x + 2y + 3z = 12
# when y and z are 0, we have 4x=12, so x=3
p3 = 3

In [210]:
p3

3

### Problem 4

Set `p4` to be the sum of the 5 axis intercepts of the following equation.

\begin{array}{rcl}
9a + 4b + 27c + 6d + 3e & = & 36 \\
\end{array}

In [211]:
# YOUR CHANGES HERE
# 9a + 4b + 27c + 6d + 3e = 36
a_int = 36/9
b_int = 36/4
c_int = 36/27
d_int = 36/6
e_int = 36/3
p4 = sum([a_int, b_int, c_int, d_int, e_int])

In [212]:
p4

32.333333333333336

### Problem 5

Set `p5` to the augmented matrix of the following system of linear equations.

\begin{array}{rcl}
3x + 2y + 13z = 10 \\
7x + 2y - 13z = 23 \\
\end{array}

In [213]:
# YOUR CHANGES HERE
# 3x + 2y + 13z = 10
# 7x + 2y - 13z = 23
p5 = np.array(
    [
        [3, 2, 13, 10],
        [7, 2, -13, 23]
    ]
)

In [214]:
p5

array([[  3,   2,  13,  10],
       [  7,   2, -13,  23]])

### Problem 6

Set `p6` to the rank of the following system of linear equations?

\begin{array}{rcl}
3x + 2y + 0z = 3 \\
2x + 3y + 1z = 5 \\
5x + 5y + 5z = 20 \\
\end{array}

In [215]:
# YOUR CHANGES HERE
"""
3x + 2y + 0z = 3
2x + 3y + 1z = 5
5x + 5y + 5z = 20

convert to row echelon form

3 2 0 3
2 3 1 5
5 5 5 20

2 3 1 5
3 2 0 3
5 5 5 20

1 1.5 .5 2.5
3 2 0 3
5 5 5 20

1 1.5 .5 2.5
0 -2.5 -1.5 -4.5
5 5 5 20

1 1.5 .5 2.5
0 1 .6 1.8
5 5 5 20

1 1.5 .5 2.5
0 1 .6 1.8
1 1 1 4

1 1.5 .5 2.5
0 1 .6 1.8
0 -.5 .5 1.5

1 1.5 .5 2.5
0 1 .6 1.8
0 1 -1 -3

1 1.5 .5 2.5
0 1 .6 1.8
0 0 -.4 -1.2

1 1.5 .5 2.5
0 1 .6 1.8
0 0 1 .3

1 1.5 .5 2.5
0 1 .6 1.8
0 0 .9 0

1 1.5 .5 2.5
0 1 .6 1.8
0 0 1 0

1 1.5 .5 2.5
0 1 0 1.8
0 0 1 0

1 0 .5 .2
0 1 0 1.8
0 0 1 0

1 0 0 .2
0 1 0 1.8
0 0 1 0

we see it converges to rank 3
"""
p6 = 3

In [216]:
p6

3

### Problem 7

Consider the following system of linear equations.

\begin{array}{rcl}
3x + 2y + 0z = 3 \\
2x + 3y + 1z = 5 \\
5x + 5y + 5z = 20 \\
\end{array}

This system could be rewritten as 
\begin{array}{rcl}
\mathbf{A}
\begin{bmatrix}
x \\ y \\ z \\
\end{bmatrix}
& = &
\begin{bmatrix}
3 \\ 5 \\ 20 \\
\end{bmatrix}
\end{array}

Set `p7` to $\mathbf{A}$.

In [217]:
# YOUR CHANGES HERE

p7 = np.array(
    [
    [3, 2, 0],
    [2, 3, 1],
    [5, 5, 5],
    ]
)

In [218]:
p7

array([[3, 2, 0],
       [2, 3, 1],
       [5, 5, 5]])

### Problem 8

Set `p8` to the number of free variables in the following system of linear equations.

\begin{array}{rcl}
x + 3y + 4z = 3 \\
0x + 0y + 1z = 2 \\
x + 3y + 5z = 5 \\
\end{array}

In [249]:
# YOUR CHANGES HERE
"""
x + 3y + 4z = 3
0x + 0y + 1z = 2
x + 3y + 5z = 5

first row reduce

1 3 4 3
0 0 1 2
1 3 5 5

1 3 4 3
0 0 1 2
1 3 4 3

1 3 4 3
0 0 1 2
0 0 0 0

1 3 0 -5
0 0 1 2
0 0 0 0
"""
p8 = 2

In [250]:
p8

2

### Problem 9

Set `p9` to any solution `(x, y, z)` to the following system of linear equations.

\begin{array}{rcl}
2x + 4y + 0z = 16 \\
1x + 3y + 1z = 16 \\
3x + 0y + 0z = 6 \\
\end{array}

In [221]:
# YOUR CHANGES HERE
"""
2x + 4y + 0z = 16  => 2x + 4y = 16  => 4 + 4y = 16 =>  4y = 12  => y=3
1x + 3y + 1z = 16  => 2 + 9 + z = 16  => z=5
3x + 0y + 0z = 6   =>   3x = 6   => x = 2
"""
p9 = 2,3,5

In [222]:
p9

(2, 3, 5)

### Problem 10

Set `p10` to any solution `(x, y, z)` to the following system of linear equations.

\begin{array}{rcl}
x + 3y + 0z = 3 \\
0x + 0y + 1z = 2 \\
\end{array}

Hint: these equations are in reduced row echelon form, so there are shortcuts to picking solutions.

In [223]:
# YOUR CHANGES HERE
"""
x + 3y + 0z = 3  => x + 3y = 3
0x + 0y + 1z = 2  => z=2

"""
p10 = (1.5, .5, 2)

In [224]:
p10

(1.5, 0.5, 2)

### Problem 11

Set `p11` to be a tuple or list of the average yields in the vineyard data set for 1989, 1990, and 1991 in that order.

In [225]:
# YOUR CHANGES HERE

p11 = [vineyard['lugs_1989'].mean(), vineyard['lugs_1990'].mean(), vineyard['target'].mean()]

In [226]:
p11

[np.float64(3.2788461538461537),
 np.float64(9.653846153846153),
 np.float64(18.08653846153846)]

### Problem 12

Set `p12` to the 95th percentile of the data in `q12`.

In [227]:
# DO NOT CHANGE

q12 = np.array([3.44857705, 2.09151799, 4.98803337, 3.8649001 , 1.20265499,
       3.89903439, 3.05276698, 0.92826333, 3.20371215, 1.81124845,
       3.53150155, 2.32418747, 1.81826697, 3.50670706, 1.37181554,
       2.95770001, 3.80008758, 2.65923837, 2.83248683, 2.91306525,
       2.18314379, 2.17931002, 2.9086665 , 3.26098354, 3.24755896,
       1.01129371, 4.56540725, 3.05517241, 2.32079938, 3.39392893,
       3.3886077 , 3.38112083, 3.88523072, 3.13214221, 3.73298754,
       4.11129171, 2.74133096, 2.4825709 , 3.21885293, 4.08327916,
       2.82768517, 2.1188981 , 3.45886466, 4.20440619, 2.25038228,
       1.59150786, 2.24486543, 3.49914959, 3.72254599, 1.84068517])

In [228]:
# YOUR ANSWER HERE

p12 = np.percentile(q12, 95)

In [229]:
p12

np.float64(4.162504674)

### Problem 13

Set `p13` to the average $L_1$ loss using the average of 1989 and 1990 vineyard yields per row to predict 1991 yields per row.

In [230]:
# YOUR CHANGES HERE
# L1 is the sum of absolute differences between pred and target
pred = (vineyard["lugs_1989"] + vineyard["lugs_1990"]).divide(2)
l1 = (vineyard["target"] - pred).abs()
p13 = l1.sum() / len(l1)

In [231]:
p13

np.float64(11.620192307692308)

### Problem 14

Build a linear regression trained with `vineyard_inputs` as its input and `vineyard_target` as its target output. Set `p14` as the output of that regression with `vineyard_inputs` as its input.

In [232]:
# YOUR CHANGES HERE
p14_linreg = sklearn.linear_model.LinearRegression().fit(vineyard_inputs, vineyard_target)
p14 = p14_linreg.predict(vineyard_inputs)

In [233]:
p14

array([12.46642263, 16.68370318, 18.66216936, 17.34319191, 19.91175065,
       18.56238423, 19.32165808, 19.68179142, 21.2307281 , 20.24149501,
       22.02039093, 20.24149501, 19.45183218, 21.3609022 , 20.90098374,
       22.58009452, 20.11132091, 22.67987965, 19.65140244, 23.33936837,
       20.90098374, 24.25920531, 20.34128014, 21.100554  , 19.78157655,
       23.89907197, 20.44106527, 22.87944991, 18.00268063, 22.77966478,
       16.68370318, 15.23455163, 15.56429599, 15.56429599, 14.90480727,
       18.00268063, 14.90480727, 16.88327344, 15.56429599, 16.88327344,
       16.22378472, 16.32356985, 15.0045924 , 16.98305857, 15.76386625,
       13.78540008, 12.46642263, 13.78540008, 13.88518521, 12.56620776,
       12.99573725,  9.69829362])

### Problem 15

Given the following data, set `p15` to the weighted variance of 

| Color | Shape | Score | Probability |
|---|---|---|---:|
| red | square | 3 | 0.250 |
| blue | circle | 4 | 0.125 |
| purple | line | 2 | 0.125 |
| purple | diamond | 5 | 0.25 |
| blue | triangle | 3 | 0.25 |

In [234]:
# YOUR CHANGES HERE
# weighted variance:
# find weighted mean, compute squared difference from each point to mean, mult each squared difference by its weight, sum weighted squared differences
# weighted mean:
# compute sum of each val mult by its weight, divided by the sum of all the weights
p15_df = pd.DataFrame(
    {
        'Color': ['red', 'blue', 'purple', 'purple', 'blue'],
        'Shape': ['square', 'circle', 'line', 'diamond', 'triangle'],
        'Score': [3, 4, 2, 5, 3],
        'Probability': [.250, .125, .125, .25, .25],
    }
)
p15_df['Score_Prob'] = p15_df['Score'] * p15_df['Probability']
weights_sum = sum(p15_df['Probability']) # 1
weighted_mean = sum(p15_df['Score_Prob']) / weights_sum # 3.5
p15 = (((p15_df['Score'] - weighted_mean) ** 2) * p15_df['Probability']).sum()

In [235]:
p15

np.float64(1.0)

### Problem 16

Set `p16` to be the correlation between the 1989 and 1990 yields in the vineyard data set.

In [236]:
# YOUR CHANGES HERE

p16 = vineyard_inputs.corr().iloc[0,1]

In [237]:
p16

np.float64(0.7224792530209384)

### Problem 17

Compute the sample mean and variance of the 1990 vineyard yields.
Assuming that the yields follow a normal distribution with your computed parameters, what would the one-sided p-value of a yield of 13 lugs be?

Hint: use the [SciPy stats module](https://docs.scipy.org/doc/scipy/reference/stats.html) to calculate the p-values from the distribution.

In [238]:
# YOUR CHANGES HERE
s_mean = vineyard_inputs['lugs_1990'].mean() #9.653846153846153
s_var = vineyard_inputs['lugs_1990'].var() #5.466063348416289
p17 = 1 - scipy.stats.norm.cdf(13, loc=s_mean, scale=math.sqrt(s_var))

In [239]:
p17

np.float64(0.07618255849601963)

### Problem 18

Set `p18` to be the $2 \times 3$ matrix full of question marks below, filled in with the following information.
1. Each serving of noodles requires 1/2 cup of flour.
2. Each serving of noodles requires 1/8 cup of water.
3. Noodles do not need sugar.
4. Each serving of cake requires 1/4 cup of flour.
5. Each serving of cake requires 1/4 cup of sugar.
6. Cake does not need water.

\begin{array}{rcl}
\begin{bmatrix}
\text{servings of noodles} & \text{pieces of cake} \\
\end{bmatrix}
\begin{bmatrix}
\text{??} & \text{??} & \text{??} \\
\text{??} & \text{??} & \text{??} \\
\end{bmatrix}
& = &
\begin{bmatrix}
\text{flour needed} & \text{sugar needed} & \text{water needed} \\
\end{bmatrix}
\end{array}

In [240]:
# YOUR CHANGES HERE

p18 = np.array(
    [
        [1/2, 0, 1/8],
        [1/4, 1/4, 0],
    ]
)

In [241]:
p18

array([[0.5  , 0.   , 0.125],
       [0.25 , 0.25 , 0.   ]])

### Problem 19

Set `p19` to be the cosine similarity of the vectors `x19` and `y19`.


In [242]:
# DO NOT CHANGE

x19 = [0.4, 0.2, -0.5]
x19

[0.4, 0.2, -0.5]

In [243]:
# DO NOT CHANGE

y19 = [-0.3, -0.2, 0.4]
y19

[-0.3, -0.2, 0.4]

In [244]:
# YOUR CHANGES HERE
num = np.array(x19) @ np.array(y19)
div = np.linalg.norm(x19) * (np.linalg.norm(y19)) # TODO not sure if I used right symbol for non dot product mult
p19 = num / div

In [245]:
p19

np.float64(-0.9965457582448795)

### Problem 20

Set `p20` to the reduced row echelon form of `q20`.


In [246]:
# DO NOT CHANGE

"""
 2   5  -3   2
-2   1   3  -2
 4   1   0   16

 2   5  -3   2
-2   1   3  -2
 0   2   6   12

 2   5  -3   2
-2   1   3  -2
 0   1   3   6

 0   6   0   0
-2   1   3  -2
 0   1   3   6

-2   1   3  -2
 0   1   0   0
 0   1   3   6

-2   0   3  -2
 0   1   0   0
 0   0   3   6

-2   0   0  -8
 0   1   0   0
 0   0   3   6

1   0   0   4
0   1   0   0
0   0   3   6

1   0   0   4
0   1   0   0
0   0   1   2
"""

q20 = np.array([[2., 5., -3., 2.0],
                [-2, 1, 3, -2],
                [ 4.,  1.,  0., 16.]])

In [247]:
# YOUR CHANGES HERE

p20 = np.array([
    [1, 0, 0, 4],
    [0, 1, 0, 0],
    [0, 0, 1, 2],
])

In [248]:
p20

array([[1, 0, 0, 4],
       [0, 1, 0, 0],
       [0, 0, 1, 2]])

### Generative AI Usage

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the [generative AI policy](https://www.bu.edu/cds-faculty/culture-community/gaia-policy/).
If you did not use any generative AI tools, simply write NONE below.

None